name: PopulationDensity
main: me.offluffy.populationdensity.PopulationDensity
version: ${pluginversion}
description: Spreads out new players to reduce tedious server joins.
authors: [jkcclemens, OffLuffy, bigscary, cindy_k]
depend: [Vault]
softdepend: [Multiverse-Core, My Worlds, Transporter, MystCraft, GriefPrevention, WorldGuard]

commands:
  populationdensity:
    description: Main command and help
    usage: /populationdensity
    aliases: [pd,pdensity]
  visitregion:
    description: Teleports the player to a specified region.
    usage: /visitregion <region name>
  homeregion:
    description: Returns the player to his/her home region.
    usage: /homeregion
  movein:
    description: Updates a user's home region to his current region.
    usage: /movein
  nameregion:
    description: Names a wilderness region.
    usage: /nameregion <name>
    permission: populationdensity.addregion
  whichregion:
    description: Tells the player which region he's in.
    usage: /WhichRegion
  newestregion:
    description: Teleports the player to the newest region.
    usage: /newestregion
  spawnregion:
    description: Teleports the player to the default spawn or default city region.
    usage: /spawnregion
    aliases: [cityregion]
  addregion:
    description: Closes the current open region and opens a new one.
    usage: /addregion
    permission: populationdensity.addregion
  scanregion:
    description: Scans the region you're standing in for resources.
    usage: /scanregion
    permission: populationdensity.addregion
  addregionpost:
    description: Generates a region post at the center of the current region.
    usage: /AddRegionPost
    permission: populationdensity.addregion
    aliases: [addpost]
  randomregion:
    description: Teleports the player to a random region.
    usage: /randomregion
  invitetoregion:
    description: Invites a player to move into your home region.
    usage: /InviteToRegion <player name>
  acceptregioninvite:
    description: Accepts an invitation to move into another player's home region.
    usage: /acceptregioninvite
  listregions:
    description: Lists current regions
    usage: /listregions
  loginpriority:
    description: Sets the login priority for a player.
    usage: /LoginPriority <player name> <priority, 0 - 100>
    permission: populationdensity.setloginpriority

permissions:
  populationdensity.*:
    description: Grants all administrative privileges.
    default: op
    children:
      populationdensity.newestregion: true
      populationdensity.buildbreakanywhere: true
      populationdensity.teleportanywhere: true
      populationdensity.createteleportsign: true
      populationdensity.useteleportsign: true
      populationdensity.addregion: true
      populationdensity.listregions: true
      populationdensity.idle: true
      populationdensity.adminlogin: true
      populationdensity.setloginpriority: true
      populationdensity.addpost: true
  populationdensity.noteleport:
    description: Denies all teleport privileges.
    default: false
    children:
      populationdensity.teleportanywhere: false
      populationdensity.cityteleport: false
      populationdensity.hometeleport: false
      populationdensity.whichregion: false
      populationdensity.newestregion: false
      populationdensity.randomteleport: false
      populationdensity.visitregion: false
      populationdensity.invitetoregion: false
      populationdensity.acceptinvite: false
  populationdensity.help:
    description: Grants permission to /pd command.
    default: true
  populationdensity.buildbreakanywhere:
    description: Grants permission to edit anywhere in the managed world, including region posts.
    default: op
  populationdensity.addpost:
    description: Grants permission to regenerate or add a region pst
    default: op
  populationdensity.movein:
    description: Grants permission to /movein command.
    default: true
  populationdensity.teleportanywhere:
    description: Grants permission to use region-based teleportation from any location.
    default: op
  populationdensity.cityteleport:
    description: Grants permission to /cityregion command.
    default: true
  populationdensity.hometeleport:
    description: Grants permission to /homeregion command.
    default: true
  populationdensity.whichregion:
    description: Grants permission to /whichregion command
    default: true
  populationdensity.newestregion:
    description: Grants permission to /newestregion command
    default: op
  populationdensity.randomteleport:
    description: Grants permission to /randomregion command
    default: op
  populationdensity.visitregion:
    description: Grants permission to /visitregion command.
    default: true
  populationdensity.invitetoregion:
    description: Grants permission to /invitetoregion command.
    default: true
  populationdensity.acceptinvite:
    description: Grants permission to accept region invitations
    default: true
  populationdensity.createteleportsign:
    description: Grants permission to create teleport signs
    default: op
  populationdensity.useteleportsign:
    description: Grants permission to use teleport signs
    default: op
  populationdensity.addregion:
    description: Grants permission to the /addregion command.
    default: op
  populationdensity.listregions:
    description: Grants permission to the /listregions command.
    default: op
  populationdensity.idle:
    description: Grants a player permission to idle (without being kicked).
    default: op
  populationdensity.adminlogin:
    description: Grants a player permission to fill a player slot reserved for administrators.
    default: op
  populationdensity.prioritylogin:
    description: Raises a player's login priority level to 25 of 100.
    default: false
  populationdensity.elitelogin:
    description: Raises a player's login priority level to 50 of 100.
    default: false
  populationdensity.setloginpriority:
    description: Grants a player permission to use /SetLoginPriority.
    default: op
